"""purchase order changes

Revision ID: a1387960c3ce
Revises: 
Create Date: 2026-06-30 06:30:54.283714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1387960c3ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('expected_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('property_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('purchase_orders_request_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ingredients', ['ingredient_id'], ['id'])
        batch_op.create_foreign_key(None, 'properties', ['property_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.drop_column('expected_delivery')
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('expected_delivery', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('purchase_orders_request_id_fkey'), 'purchase_requests', ['request_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('property_id')
        batch_op.drop_column('expected_date')
        batch_op.drop_column('ingredient_id')

    # ### end Alembic commands ###
